<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\CLHelpdesk\CLHelpdesk.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Include="..\helpdesk_tickets.csv">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <Link>helpdesk_tickets.csv</Link>
    </None>
  </ItemGroup>

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

</Project>
